#!/usr/bin/env bash
#   █████╗ ██████╗ ██████╗ ███████╗    ██╗      █████╗ ██╗   ██╗███╗   ██╗ ██████╗██╗  ██╗███████╗██████╗
#  ██╔══██╗██╔══██╗██╔══██╗██╔════╝    ██║     ██╔══██╗██║   ██║████╗  ██║██╔════╝██║  ██║██╔════╝██╔══██╗
#  ███████║██████╔╝██████╔╝███████╗    ██║     ███████║██║   ██║██╔██╗ ██║██║     ███████║█████╗  ██████╔╝
#  ██╔══██║██╔═══╝ ██╔═══╝ ╚════██║    ██║     ██╔══██║██║   ██║██║╚██╗██║██║     ██╔══██║██╔══╝  ██╔══██╗
#  ██║  ██║██║     ██║     ███████║    ███████╗██║  ██║╚██████╔╝██║ ╚████║╚██████╗██║  ██║███████╗██║  ██║
#  ╚═╝  ╚═╝╚═╝     ╚═╝     ╚══════╝    ╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
#	Script to control preferred apps to launch for all themes
# 	Author: z0mbi3
#	url: https://github.com/gh0stzk

WIDGET_DIR="$HOME/.config/bspwm/eww"

case "$1" in
--menu)
	rofi -show drun -theme $HOME/.config/bspwm/scripts/Launcher.rasi
	;;
--rice)
	RiceSelector
	;;
--terminal)
	alacritty
	;;
--floating)
	alacritty --class FloaTerm,Alacritty \
		-o window.dimensions.lines=22 \
		window.dimensions.columns=90
	;;
--update)
	alacritty --hold --class FloaTerm,Alacritty \
		-o window.dimensions.lines=22 \
		window.dimensions.columns=90 \
		-e Updates --update-system
	;;
--checkupdates)
	alacritty --hold --class Updating,Alacritty -o window.dimensions.lines=22 window.dimensions.columns=47 -e Updates --print-updates
	;;
--ranger)
	alacritty --class FloaTerm,Alacritty -o window.dimensions.lines=14 window.dimensions.columns=90 -e ranger
	;;
--nvim)
	alacritty -e nvim
	;;
--music)
	alacritty --class FloaTerm,Alacritty -o window.dimensions.lines=18 window.dimensions.columns=67 -e ncmpcpp
	;;
--fetch)
	alacritty --hold --class FloaTerm,Alacritty -o window.dimensions.lines=26 window.dimensions.columns=40 -e ~/.local/bin/sysfetch
	;;
# Apps
--filemanager)
	nautilus
	;;
--browser)
	firefox
	;;
--editor)
	geany
	;;
--telegram)
	telegram-desktop
	;;
--whats)
	whatsapp-nativefier --disable-gpu
	;;
--soundcontrol)
	pavucontrol
	;;
--spotify)
	spotify-launcher
	;;
# Eww Widgets
--powermenu)
	eww -c "$WIDGET_DIR" open --toggle powermenu
	;;
--usercard)
	eww -c "$WIDGET_DIR" open --toggle launchermenu
	;;
--player)
	eww -c "$WIDGET_DIR" open --toggle music
	;;
--calendar)
	eww -c "$WIDGET_DIR" open --toggle date
	;;
--network)
	eww -c "$WIDGET_DIR" open --toggle wifiMenu
	;;
--bluetooth)
	eww -c "$WIDGET_DIR" open --toggle bluetoothMenu
	;;
--firstNetwork)
	alacritty --class FloaTerm,Alacritty -o window.dimensions.lines=15 \
		window.dimensions.columns=55 -e ~/.config/bspwm/scripts/Networks.sh --firstNet
	;;
--secondNetwork)
	alacritty --class FloaTerm,Alacritty -o window.dimensions.lines=15 \
		window.dimensions.columns=55 -e ~/.config/bspwm/scripts/Networks.sh --secondNet
	;;
--thirdNetwork)
	alacritty --class FloaTerm,Alacritty -o window.dimensions.lines=15 \
		window.dimensions.columns=55 -e ~/.config/bspwm/scripts/Networks.sh --thirdNet
	;;
--bluetoothFirstDevice)
	alacritty --class FloaTerm,Alacritty -o window.dimensions.line=15 window.dimensions.columns=55 -e ~/.config/bspwm/scripts/bluetoothStatus.sh --bluetoothFirstDevice
	;;

--bluetoothSecondDevice)
	alacritty --class FloaTerm,Alacritty -o window.dimensions.line=15 window.dimensions.coumns=55 -e ~/.config/bspwm/scripts/bluetoothStatus.sh --bluetoothSecondDevice
	;;
--bluetoothManager)
	blueman-manager
	;;

--bluetoothOn)
	rfkill unblock bluetooth
	;;

--bluetoothOff)
	rfkill block bluetooth
	;;

--powerStatus)
	~/.config/bspwm/scripts/powerStatus.sh
	;;

*)
	echo "Opción no válida"
	;;
esac
