#!/usr/bin/env bash
#  ╔═╗╔═╗╔═╗╔═╗  ╦  ╔═╗╦ ╦╔╗╔╔═╗╦ ╦╔═╗╦═╗
#  ╠═╣╠═╝╠═╝╚═╗  ║  ╠═╣║ ║║║║║  ╠═╣║╣ ╠╦╝
#  ╩ ╩╩  ╩  ╚═╝  ╩═╝╩ ╩╚═╝╝╚╝╚═╝╩ ╩╚═╝╩╚═
#	Script to control apps launcher
#   Author: z0mbi3
#	url: https://github.com/gh0stzk

# From here you can control your favorite applications for all themes.

case "$1" in
  --menu)
    rofi -show drun \
		 -theme $HOME/.config/bspwm/rices/${RICETHEME}/launcher.rasi;;

  --rice)
	RiceSelector;;

  --terminal)
    alacritty;;

  --floating)
    alacritty --class FloaTerm,Alacritty \
					-o window.dimensions.lines=22 \
					window.dimensions.columns=90;;

  --update)
    alacritty --hold --class FloaTerm,Alacritty \
					-o window.dimensions.lines=22 \
					   window.dimensions.columns=90 \
					-e Updates --update-system;;

  --checkupdates)
	alacritty --hold --class Updating,Alacritty \
					-o window.dimensions.lines=22 \
					   window.dimensions.columns=47 \
					-e Updates --print-updates;;

  --ranger)
    alacritty --class FloaTerm,Alacritty \
					-o window.dimensions.lines=14 \
					   window.dimensions.columns=90 \
					-e ranger;;

  --nvim)
    alacritty -e nvim;;

  --music)
    alacritty --class FloaTerm,Alacritty \
					-o window.dimensions.lines=18 \
					   window.dimensions.columns=67 \
					-e ncmpcpp;;

  --fetch)
    alacritty --hold --class FloaTerm,Alacritty \
					-o window.dimensions.lines=26 \
					   window.dimensions.columns=40 \
					-e ~/.local/bin/sysfetch;;
  --firstNetwork)
     alacritty --class FloaTerm,Alacritty\
                    -o window.dimensions.lines=15 \
                       window.dimensions.columns=55\
                    -e ~/.config/bspwm/scripts/Networks.sh --firstNet;;
  
  --secondNetwork)
     alacritty --class FloaTerm,Alacritty\
                    -o window.dimensions.lines=15 \
                       window.dimensions.columns=55\
                    -e ~/.config/bspwm/scripts/Networks.sh --secondNet;;

  --thirdNetwork)
     alacritty --class FloaTerm,Alacritty\
                    -o window.dimensions.lines=15 \
                       window.dimensions.columns=55\
                    -e ~/.config/bspwm/scripts/Networks.sh --thirdNet;;

  --bluetoothFirstDevice)
    alacritty --class FloaTerm,Alacritty\
                    -o window.dimensions.line=15\
                       window.dimensions.columns=55\
                    -e ~/.config/bspwm/scripts/bluetoothStatus.sh --bluetoothFirstDevice;;
  
  --bluetoothSecondDevice)
    alacritty --class FloaTerm,Alacritty\
                    -o window.dimensions.line=15\
                       window.dimensions.coumns=55\
                    -e ~/.config/bspwm/scripts/bluetoothStatus.sh --bluetoothSecondDevice;;
  #Apps

  --spotify)
    spotify-launcher;;

  --sublimetext)
    subl;;

  --filemanager)
	nautilus;;

  --browser)
	firefox;;

  --editor)
	geany;;

  --telegram)
	telegram;;

  --whats)
	whatsapp-nativefier --disable-gpu;;

  --soundcontrol)
    pavucontrol;;

  --bluetooth)
    blueman-manager;;

  --bluetoothOn)
    rfkill unblock bluetooth;;
  
  --bluetoothOff)
    rfkill block bluetooth;;

  --firstNetwork)
    firstNetwork;;
  
  --secondNetwork)
    secondNetwork;;
  
  --thirdNetwork)
    thirdNetwork;;

  --bluetoothFirstDevice)
    bluetoothFirstDevice;;

  --bluetoothSecondDevice)
    bluetoothSecondDevice;;

  *)
    echo "Opción no válida";;
esac
